// <auto-generated />
namespace Infraestructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v2CodeLastName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v2CodeLastName));
        
        string IMigrationMetadata.Id
        {
            get { return "202206130301369_v2Code&LastName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
